compile:
	gcc parte1.c inputs_part1.c -o p1 -lm  

lru-0:
	./p1 lru 0 > lru00.out  

lru-1:
	./p1 lru 1 > lru01.out 

lru-2:
	./p1 lru 2 > lru02.out     

lru-3:
	./p1 lru 3 > lru03.out 

lru-4:
	./p1 lru 4 > lru04.out 

lru-5:
	./p1 lru 5 > lru05.out 

fifo-0:
	./p1 fifo 0 > fifo00.out  

fifo-1:
	./p1 fifo 1 > fifo01.out  

fifo-2:
	./p1 fifo 2 > fifo02.out 

fifo-3:
	./p1 fifo 3 > fifo03.out  

fifo-4:
	./p1 fifo 4 > fifo04.out  

fifo-5:
	./p1 fifo 5 > fifo05.out  

clean:
	rm -f p1 fifo00.out lru00.out fifo01.out lru01.out   fifo02.out lru02.out   fifo03.out lru03.out    fifo04.out lru04.out    fifo05.out lru05.out                   