# Base de dados
db.host=localhost
db.name=Tabela_SD
db.schema=biblioteca
db.user=postgres

db.password=1234

# RMI
rmi.host=localhost
rmi.port=1099

# Servidor admin TCP
admin.host=localhost
admin.port=6000
