compile:
	gcc queue.c inputs_part2.c pt2.c -o simulador -lm

run0:
	./simulador 0 > output2T00.out                           

run1:
	./simulador 1 > output2T01.out

run2:
	./simulador 2 > output2T02.out
run3:
	./simulador 3 > output2T03.out	
run4:
	./simulador 4 > output2T04.out
run5:
	./simulador 5 > output2T05.out
run6:
	./simulador 6 > output2T06.out
run7:
	./simulador 7 > output2T07.out	
run8:
	./simulador 8 > output2T08.out
run9:
	./simulador 9 > output2T09.out
run10:
	./simulador 10 > output2T10.out
run11:
	./simulador 11 > output2T11.out


clean:
	rm -f simulador output2T00.out output2T01.out output2T02.out output2T03.out output2T04.out output2T05.out output2T06.out output2T07.out output2T08.out output2T09.out output2T10.out output2T11.out
