compile:
	gcc queue.c inputs.c Final.c -o simulador  

run0:
	./simulador 0 > output00.out                           
run1:
	./simulador 1 >output01.out                           
run2:
	./simulador 2 >output02.out                           
run3:
	./simulador 3 >output03.out                           
run4:
	./simulador 4 >output04.out                           
run5:
	./simulador 5 >output05.out                           

clean:
	rm -f simulador output00.out output01.out output02.out output03.out output04.out output05.out                       